### ISSUE TITLE
Text input ignoring

### ISSUE THREAD

**Issue by Aeroxia** [OldPlanets/Wireboard#1] opened 2019-01-15 05:05 UTC
Every now and then after a certain amount of text is entered and I pause typing for a brief moment, the borders go red and it stops registering input. The pause can be short enough that mid-sentence or mid-word it locks up and just doesn't accept a bunch of letters, so I have to stop and look and retype from where it fell out of sync.

I guess it's pausing while it gets the text entered from the phone? Because pasting some text and then pressing something on PC seems to make it do it each time, then updates the pasted text. It's really disruptive to typing and uncomfortable though.

**Comment by OldPlanets** [comment] 2019-01-22 16:58
If the border flashes red that means there a synchronization error was detected, meaning the text on your phone is not the same as it is on your local client where you are typing. It is kinda meant to be disruptive and force you to look, because there is no easy way to resolve the issue other then to copy over the text from your phone back to your local client and that means changing something which you didn't type in that moment or reverting keystrokes you just entered.
The question is why it's happening, because usually an out of sync event happens only when a) you type on your phone (and change the input text there) or b) the input field of the app has some kind of filter or post-processing. For example when a field allows only number and you type a letter, such a forced sync will happen.
Is it one specifc app or does it happen all the time (so for example in the test textbox of the wireboard app)?

**Comment by OldPlanets** [comment] 2019-01-22 19:48
Mhm, indeed, you are right. I was able to reproduce it, using the enter key sometimes seems to cause problems why typing fast. I'm usually using messenger apps which sent the text once you hit enter, so I never really noticed before.
I'll look into it once I find the time for it, I'm pretty sure it can be fixed soon. Thanks for reporting :)

**Comment by OldPlanets** [comment] 2019-01-31 10:49
The bug has been fixed in the 1.02 update for the android app. (no need to update the windows client)

**Closed by OldPlanets** 2019-01-31 10:49 UTC
Labels: bug
